/* ==========================================================================
 * js/chat/emoji-data.js
 * Emoji picker data, quick reactions and :shortcode: expansion
 * Loaded by js/loader.js (load order lives in js/manifest.js).
 * All js files share one global scope, so functions/consts here are visible to the others.
 * ========================================================================== */
'use strict';

/* ---------- Emoji picker data (message composer) ---------- */
const QUICK_REACT=['👍','❤️','😂','😮','😢','🔥'];
// Each entry is [emoji, shortcode-name]. Names power the Discord-style :name: search
// (e.g. ":sob:" -> 😭) as well as the "browse" grid tooltip.
const EMOJI_CATS=[
  {n:'Smileys',ic:'😀',list:[['😀','grinning'],['😃','smiley'],['😄','smile'],['😁','grin'],['😆','laughing'],['😅','sweat_smile'],['🤣','rofl'],['😂','joy'],['🙂','slight_smile'],['🙃','upside_down'],['😉','wink'],['😊','blush'],['😇','innocent'],['🥰','heart_eyes_hug'],['😍','heart_eyes'],['🤩','star_struck'],['😘','kissing_heart'],['😗','kissing'],['😚','kissing_closed_eyes'],['😙','kissing_smiling_eyes'],['😋','yum'],['😛','stuck_out_tongue'],['😜','stuck_out_tongue_winking_eye'],['🤪','zany_face'],['😝','stuck_out_tongue_closed_eyes'],['🤑','money_mouth'],['🤗','hugs'],['🤭','hand_over_mouth'],['🤫','shushing'],['🤔','thinking'],['🤐','zipper_mouth'],['🤨','raised_eyebrow'],['😐','neutral_face'],['😑','expressionless'],['😶','no_mouth'],['😏','smirk'],['😒','unamused'],['🙄','roll_eyes'],['😬','grimacing'],['🤥','lying_face'],['😌','relieved'],['😔','pensive'],['😪','sleepy'],['🤤','drooling'],['😴','sleeping'],['😷','mask'],['🤒','thermometer_face'],['🤕','head_bandage'],['🤢','nauseated'],['🤮','vomiting'],['🥵','hot_face'],['🥶','cold_face'],['🥴','woozy'],['😵','dizzy_face'],['🤯','exploding_head'],['🤠','cowboy'],['🥳','partying'],['😎','sunglasses'],['🤓','nerd'],['🧐','monocle'],['😕','confused'],['😟','worried'],['🙁','slight_frown'],['☹️','frowning'],['😮','open_mouth'],['😯','hushed'],['😲','astonished'],['😳','flushed'],['🥺','pleading'],['😦','frowning_open_mouth'],['😧','anguished'],['😨','fearful'],['😰','cold_sweat'],['😥','disappointed_relieved'],['😢','cry'],['😭','sob'],['😱','scream'],['😖','confounded'],['😣','persevere'],['😞','disappointed'],['😓','downcast_sweat'],['😩','weary'],['😫','tired_face'],['🥱','yawning'],['😤','triumph'],['😡','rage'],['😠','angry'],['🤬','cursing'],['😈','smiling_imp'],['👿','imp'],['💀','skull'],['☠️','skull_crossbones'],['💩','poop'],['🤡','clown'],['👻','ghost'],['👽','alien'],['🤖','robot']]},
  {n:'Gestures',ic:'👍',list:[['👋','wave'],['🤚','raised_back_of_hand'],['🖐️','raised_hand_fingers'],['✋','raised_hand'],['🖖','vulcan'],['👌','ok_hand'],['🤌','pinched_fingers'],['🤏','pinching'],['✌️','v'],['🤞','crossed_fingers'],['🤟','love_you_gesture'],['🤘','metal'],['🤙','call_me'],['👈','point_left'],['👉','point_right'],['👆','point_up_2'],['🖕','middle_finger'],['👇','point_down'],['☝️','point_up'],['👍','thumbsup'],['👎','thumbsdown'],['✊','fist'],['👊','fist_oncoming'],['🤛','fist_left'],['🤜','fist_right'],['👏','clap'],['🙌','raised_hands'],['👐','open_hands'],['🤲','palms_up'],['🤝','handshake'],['🙏','pray'],['✍️','writing_hand'],['💅','nail_care'],['🤳','selfie'],['💪','muscle'],['🦾','mechanical_arm'],['🦵','leg'],['🦶','foot'],['👂','ear'],['🦻','ear_hearing_aid'],['👃','nose'],['🧠','brain'],['🫀','heart_organ'],['🦷','tooth'],['👀','eyes'],['👁️','eye'],['👅','tongue'],['👄','lips']]},
  {n:'Hearts',ic:'❤️',list:[['❤️','heart'],['🧡','orange_heart'],['💛','yellow_heart'],['💚','green_heart'],['💙','blue_heart'],['💜','purple_heart'],['🖤','black_heart'],['🤍','white_heart'],['🤎','brown_heart'],['💔','broken_heart'],['❣️','heart_exclamation'],['💕','two_hearts'],['💞','revolving_hearts'],['💓','heartbeat'],['💗','heartpulse'],['💖','sparkling_heart'],['💘','cupid'],['💝','gift_heart'],['💟','heart_decoration'],['☮️','peace'],['✝️','cross'],['☪️','star_and_crescent'],['🕉️','om'],['☸️','wheel_of_dharma']]},
  {n:'Animals',ic:'🐶',list:[['🐶','dog'],['🐱','cat'],['🐭','mouse'],['🐹','hamster'],['🐰','rabbit'],['🦊','fox'],['🐻','bear'],['🐼','panda'],['🐨','koala'],['🐯','tiger'],['🦁','lion'],['🐮','cow'],['🐷','pig'],['🐸','frog'],['🐵','monkey'],['🙈','see_no_evil'],['🙉','hear_no_evil'],['🙊','speak_no_evil'],['🐒','monkey_face'],['🐔','chicken'],['🐧','penguin'],['🐦','bird'],['🐤','baby_chick'],['🦆','duck'],['🦅','eagle'],['🦉','owl'],['🦇','bat'],['🐺','wolf'],['🐗','boar'],['🐴','horse'],['🦄','unicorn'],['🐝','bee'],['🐛','bug'],['🦋','butterfly'],['🐌','snail'],['🐞','ladybug'],['🐜','ant'],['🦗','cricket'],['🕷️','spider'],['🦂','scorpion'],['🐢','turtle'],['🐍','snake'],['🦎','lizard'],['🦖','trex'],['🦕','sauropod'],['🐙','octopus'],['🦑','squid'],['🦐','shrimp'],['🦀','crab'],['🐡','blowfish'],['🐠','tropical_fish'],['🐟','fish'],['🐬','dolphin'],['🐳','whale'],['🐋','whale2'],['🦈','shark'],['🐊','crocodile'],['🐅','tiger2'],['🐆','leopard'],['🦓','zebra'],['🦍','gorilla'],['🦧','orangutan'],['🐘','elephant'],['🦛','hippo'],['🦏','rhino'],['🐪','camel'],['🐫','camel2'],['🦒','giraffe'],['🦘','kangaroo'],['🐃','water_buffalo'],['🐂','ox'],['🐄','cow2'],['🐎','racehorse'],['🐖','pig2'],['🐏','ram'],['🐑','sheep'],['🦙','llama'],['🐐','goat'],['🦌','deer'],['🐕','dog2'],['🐩','poodle'],['🐈','cat2'],['🐓','rooster'],['🦃','turkey'],['🦚','peacock'],['🦜','parrot'],['🦢','swan'],['🦩','flamingo'],['🕊️','dove'],['🐇','rabbit2'],['🦝','raccoon'],['🦨','skunk'],['🦡','badger'],['🦦','otter'],['🦥','sloth'],['🐁','mouse2'],['🐀','rat'],['🐿️','chipmunk']]},
  {n:'Food',ic:'🍕',list:[['🍏','green_apple'],['🍎','apple'],['🍐','pear'],['🍊','tangerine'],['🍋','lemon'],['🍌','banana'],['🍉','watermelon'],['🍇','grapes'],['🍓','strawberry'],['🫐','blueberries'],['🍈','melon'],['🍒','cherries'],['🍑','peach'],['🥭','mango'],['🍍','pineapple'],['🥥','coconut'],['🥝','kiwi'],['🍅','tomato'],['🍆','eggplant'],['🥑','avocado'],['🥦','broccoli'],['🥬','leafy_green'],['🥒','cucumber'],['🌶️','hot_pepper'],['🫑','bell_pepper'],['🌽','corn'],['🥕','carrot'],['🧄','garlic'],['🧅','onion'],['🥔','potato'],['🍠','sweet_potato'],['🥐','croissant'],['🥯','bagel'],['🍞','bread'],['🥖','baguette'],['🥨','pretzel'],['🧀','cheese'],['🥚','egg'],['🍳','fried_egg'],['🧈','butter'],['🥞','pancakes'],['🧇','waffle'],['🥓','bacon'],['🥩','cut_of_meat'],['🍗','poultry_leg'],['🍖','meat_on_bone'],['🌭','hotdog'],['🍔','hamburger'],['🍟','fries'],['🍕','pizza'],['🥪','sandwich'],['🥙','stuffed_flatbread'],['🧆','falafel'],['🌮','taco'],['🌯','burrito'],['🥗','salad'],['🥘','shallow_pan_of_food'],['🍝','spaghetti'],['🍜','ramen'],['🍲','stew'],['🍛','curry'],['🍣','sushi'],['🍱','bento'],['🥟','dumpling'],['🍤','fried_shrimp'],['🍙','rice_ball'],['🍚','rice'],['🍘','rice_cracker'],['🍥','fish_cake'],['🥠','fortune_cookie'],['🥮','moon_cake'],['🍢','oden'],['🍡','dango'],['🍧','shaved_ice'],['🍨','ice_cream'],['🍦','soft_ice_cream'],['🥧','pie'],['🧁','cupcake'],['🍰','cake'],['🎂','birthday'],['🍮','custard'],['🍭','lollipop'],['🍬','candy'],['🍫','chocolate'],['🍿','popcorn'],['🍩','doughnut'],['🍪','cookie'],['🌰','chestnut'],['🥜','peanuts'],['🍯','honey_pot'],['🥛','milk'],['🍼','baby_bottle'],['☕','coffee'],['🍵','tea'],['🧃','juice'],['🥤','cup_with_straw'],['🍶','sake'],['🍺','beer'],['🍻','beers'],['🥂','clink'],['🍷','wine'],['🥃','whiskey'],['🍸','cocktail'],['🍹','tropical_drink'],['🧉','mate'],['🍾','champagne']]},
  {n:'Activities',ic:'⚽',list:[['⚽','soccer'],['🏀','basketball'],['🏈','football'],['⚾','baseball'],['🥎','softball'],['🎾','tennis'],['🏐','volleyball'],['🏉','rugby'],['🥏','frisbee'],['🎱','8ball'],['🪀','yoyo'],['🏓','ping_pong'],['🏸','badminton'],['🏒','hockey'],['🏑','field_hockey'],['🥍','lacrosse'],['🏏','cricket_bat'],['🥅','goal'],['⛳','golf'],['🪁','kite'],['🏹','bow_arrow'],['🎣','fishing_pole'],['🤿','diving_mask'],['🥊','boxing_glove'],['🥋','martial_arts'],['🎽','running_shirt'],['🛹','skateboard'],['🛼','roller_skate'],['🛷','sled'],['⛸️','ice_skate'],['🥌','curling_stone'],['🎿','ski'],['⛷️','skier'],['🏂','snowboarder'],['🪂','parachute'],['🏋️','weight_lifting'],['🤸','cartwheel'],['🤺','fencing'],['🤾','handball'],['🏌️','golfer'],['🏇','horse_racing'],['🧘','lotus_position'],['🏄','surfer'],['🏊','swimmer'],['🤽','water_polo'],['🚣','rowboat'],['🧗','climbing'],['🚵','mountain_biking'],['🚴','biking'],['🏆','trophy'],['🥇','gold_medal'],['🥈','silver_medal'],['🥉','bronze_medal'],['🏅','medal'],['🎖️','military_medal'],['🎗️','reminder_ribbon'],['🎫','ticket'],['🎟️','tickets'],['🎪','circus_tent'],['🤹','juggling'],['🎭','performing_arts'],['🩰','ballet_shoes'],['🎨','art'],['🎬','clapper'],['🎤','microphone'],['🎧','headphones'],['🎼','musical_score'],['🎹','piano'],['🥁','drum'],['🎷','saxophone'],['🎺','trumpet'],['🎸','guitar'],['🪕','banjo'],['🎻','violin'],['🎮','video_game'],['🕹️','joystick'],['🎲','game_die'],['♟️','chess_pawn'],['🧩','puzzle']]},
  {n:'Objects',ic:'💡',list:[['⌚','watch'],['📱','iphone'],['💻','computer'],['⌨️','keyboard'],['🖥️','desktop'],['🖨️','printer'],['🖱️','mouse3'],['💽','minidisc'],['💾','floppy_disk'],['💿','cd'],['📀','dvd'],['🎥','movie_camera'],['📷','camera'],['📸','camera_flash'],['📹','video_camera'],['📼','vhs'],['🔍','mag'],['🔦','flashlight'],['💡','bulb'],['🏮','lantern'],['🪔','diya_lamp'],['📔','notebook_decorative'],['📕','closed_book'],['📖','open_book'],['📗','green_book'],['📘','blue_book'],['📙','orange_book'],['📚','books'],['📓','notebook'],['📒','ledger'],['📃','page_curl'],['📜','scroll'],['📄','page_facing_up'],['📰','newspaper'],['🗞️','rolled_newspaper'],['🔖','bookmark'],['🏷️','label'],['💰','moneybag'],['💴','yen'],['💵','dollar'],['💶','euro'],['💷','pound'],['💸','money_wings'],['💳','credit_card'],['🧾','receipt'],['✉️','envelope'],['📩','envelope_arrow'],['📨','incoming_envelope'],['📧','email'],['💌','love_letter'],['📥','inbox_tray'],['📤','outbox_tray'],['📦','package'],['📫','mailbox'],['📪','mailbox_closed'],['📬','mailbox_open'],['📭','mailbox_empty'],['📮','postbox'],['🗳️','ballot_box'],['✏️','pencil'],['✒️','pen'],['🖋️','fountain_pen'],['🖊️','pen2'],['🖌️','paintbrush'],['🖍️','crayon'],['📝','memo'],['💼','briefcase'],['📁','folder'],['📂','open_folder'],['🗂️','card_index'],['📅','calendar'],['📆','date'],['🗒️','spiral_notepad'],['🗓️','spiral_calendar'],['📇','card_box'],['📈','chart_up'],['📉','chart_down'],['📊','bar_chart'],['📌','pushpin'],['📍','round_pushpin'],['📎','paperclip'],['🖇️','paperclips'],['📏','ruler'],['📐','triangular_ruler'],['✂️','scissors'],['🗃️','card_file_box'],['🗄️','file_cabinet'],['🗑️','wastebasket'],['🔒','lock'],['🔓','unlock'],['🔏','lock_pen'],['🔐','locked_key'],['🔑','key'],['🗝️','old_key'],['🔨','hammer'],['🪓','axe'],['⛏️','pick'],['🔧','wrench'],['🔩','nut_and_bolt'],['⚙️','gear'],['🗜️','clamp'],['⚖️','scales'],['🦯','probing_cane'],['🔗','link'],['⛓️','chains'],['🧰','toolbox'],['🧲','magnet'],['⚗️','alembic'],['🧪','test_tube'],['🧫','petri_dish'],['🧬','dna'],['🔬','microscope'],['🔭','telescope'],['📡','satellite'],['💉','syringe'],['💊','pill'],['🩹','bandage'],['🩺','stethoscope']]},
  {n:'Symbols',ic:'⭐',list:[['✨','sparkles'],['🎉','tada'],['🎊','confetti_ball'],['🎈','balloon'],['🎁','gift'],['🏆','trophy2'],['🔥','fire'],['💯','100'],['⭐','star'],['🌟','star2'],['💫','dizzy'],['⚡','zap'],['☄️','comet'],['💥','boom'],['💢','anger'],['💦','sweat_drops'],['💨','dash'],['🕳️','hole'],['💣','bomb'],['💤','zzz'],['👑','crown'],['💎','gem'],['🔔','bell'],['🔕','no_bell'],['🎵','musical_note'],['🎶','notes'],['➕','plus'],['➖','minus'],['➗','divide'],['✖️','multiply'],['♾️','infinity'],['‼️','bangbang'],['⁉️','interrobang'],['❓','question'],['❔','white_question'],['❗','exclamation'],['❕','white_exclamation'],['〰️','wavy_dash'],['💱','currency_exchange'],['💲','heavy_dollar'],['⚕️','medical_symbol'],['♻️','recycle'],['⚜️','fleur_de_lis'],['🔱','trident'],['📛','name_badge'],['🔰','beginner'],['⭕','o'],['✅','white_check_mark'],['☑️','ballot_box_check'],['✔️','heavy_check_mark'],['❌','x'],['❎','negative_squared_x'],['➰','curly_loop'],['➿','double_curly_loop'],['〽️','part_alternation'],['✳️','eight_spoked_asterisk'],['✴️','eight_pointed_star'],['❇️','sparkle'],['©️','copyright'],['®️','registered'],['™️','tm']]}
];
// Flat lookup: "sob" -> "😭", plus a reverse map for tooltips
const EMOJI_BY_NAME={};
const EMOJI_NAME_BY_CHAR={};
EMOJI_CATS.forEach(cat=>cat.list.forEach(([e,name])=>{EMOJI_BY_NAME[name]=e;EMOJI_NAME_BY_CHAR[e]=name}));
// Extra names for emoji that people search for under a different word (":v:", ":victory:", ":peace:" -> \u270c\ufe0f).
const EMOJI_ALIASES={victory:'\u270c\ufe0f',peace:'\u270c\ufe0f',victory_hand:'\u270c\ufe0f',peace_sign:'\u270c\ufe0f',v:'\u270c\ufe0f'};
Object.keys(EMOJI_ALIASES).forEach(n=>{if(!EMOJI_BY_NAME[n])EMOJI_BY_NAME[n]=EMOJI_ALIASES[n]});
// :name search used by the composer popup. Names that START with the query come first, then names that
// merely contain it; one result per emoji; first `limit` (10) only.
function searchEmoji(q,limit){
  q=String(q||'').toLowerCase();if(!q)return[];
  const names=Object.keys(EMOJI_BY_NAME),seen=new Set(),out=[];
  const add=n=>{const e=EMOJI_BY_NAME[n];if(seen.has(e))return;seen.add(e);out.push({name:n,emoji:e})};
  names.filter(n=>n.startsWith(q)).forEach(add);
  names.filter(n=>!n.startsWith(q)&&n.includes(q)).forEach(add);
  return out.slice(0,limit||10);
}
// Matches a trailing/typed :shortcode: (allows an incomplete trailing ":name" while typing)
const SHORTCODE_RE=/:([a-z0-9_+-]{2,40}):?/gi;
// Replaces every complete :name: in a string with its emoji; unknown names pass through untouched.
function expandShortcodes(str){
  if(!str)return str;
  return str.replace(/:([a-z0-9_+-]{1,40}):/gi,(m,name)=>EMOJI_BY_NAME[name.toLowerCase()]||m);
}
